// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCl0ft7OcvO6bB_mBBlZCMHNKUSA6nEYA',
    appId: '1:469881266460:web:e984d097b076c3bb291ad9',
    messagingSenderId: '469881266460',
    projectId: 'iot-project-4c998',
    authDomain: 'iot-project-4c998.firebaseapp.com',
    storageBucket: 'iot-project-4c998.appspot.com',
    measurementId: 'G-SZ71T3BBP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAay6xqUj0Bhyxv1TbZLBHD09XMg9iPVyQ',
    appId: '1:469881266460:android:cfd3fe99045dc6a6291ad9',
    messagingSenderId: '469881266460',
    projectId: 'iot-project-4c998',
    storageBucket: 'iot-project-4c998.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3ttlESkbO1aZxc71Lo7Jz5I_LUtsIlS4',
    appId: '1:469881266460:ios:6e2502cf3b1370fb291ad9',
    messagingSenderId: '469881266460',
    projectId: 'iot-project-4c998',
    storageBucket: 'iot-project-4c998.appspot.com',
    iosClientId: '469881266460-touc81s9id792gkk8d9phg8bnjro8e4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.iotProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3ttlESkbO1aZxc71Lo7Jz5I_LUtsIlS4',
    appId: '1:469881266460:ios:6e2502cf3b1370fb291ad9',
    messagingSenderId: '469881266460',
    projectId: 'iot-project-4c998',
    storageBucket: 'iot-project-4c998.appspot.com',
    iosClientId: '469881266460-touc81s9id792gkk8d9phg8bnjro8e4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.iotProject',
  );
}
